### ISSUE TITLE
为什么数据解析的如此缓慢？

### ISSUE THREAD

**Issue by MIkeeJY** [xingrz/GankMeizhi#1]

**Comment by xingrz** [comment]
因为要将图片整张下载下来后解码测量宽高后入库，瀑布流布局需要。

实际上会耗费多一次流量，暂时无奈之举。

**Comment by ryh** [comment]
用API而不是解析html 要稳定＋快速些吧 http://gank.io/api  @xingrz

**Comment by xingrz** [comment]
我知道，只是最近还没时间更新

-- 
XiNGRZ
Sent with Airmail

在 2015年8月29日 上午9:55:03, Bigfish (notifications@github.com) 写到:

用API而不是解析html 要稳定＋快速些吧 http://gank.io/api @xingrz
