### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by tomridder** [xingrz/GankMeizhi#10]
会报空指针异常，java.lang.NullPointerException: Attempt to read from field 'boolean me.xingrz.gankmeizhi.net.GankApi$Result.error' on a null object reference
at me.xingrz.gankmeizhi.MeizhiFetchingService.fetchLatest(MeizhiFetchingService.java:152)
麻烦修复一下

**Comment by xingrz** [comment]
![image](https://user-images.githubusercontent.com/288288/57907038-a9355c80-78ae-11e9-8d4e-41dcde6e9dc8.png)

你好，麻烦留意一下说明。
