### ISSUE TITLE
在虚拟按键机型下 ViewActivity 的 Toolbar 的高度不正确

### ISSUE THREAD

**Issue by cooliean** [xingrz/GankMeizhi#4]
android:fitsSystemWindows=  如果为false搞度就对，为什么啊。

**Comment by xingrz** [comment]
是一个 BUG，因为我手机是物理按键的，所以之前没留意到这个问题。

**Comment by cooliean** [comment]
我这里确实是一个4.4的虚拟按钮，物理按键我倒是没有测试呢。
还有一个问题就是我想在你那个ViewerActivity加一个ProgressBar的轮子，不知道有什么好想法不呢，谢谢了。

**Comment by xingrz** [comment]
进度条我也想过加，但一来进度是不可知的，所以 SwipeRefreshLayout 的轮子已经够用了（虽然一开始它没有出来）

下个版本我会想办法改善加载速度的

**Comment by cooliean** [comment]
SwipeRefreshLayout的轮子已经够用了（虽然一开始它没有出来） 这个问题你用这个方法就可以了
mRefreshLayout.post(new Runnable() {
                    @Override
                    public void run() {
                        if (showRefreshView) {
                            mRefreshLayout.setRefreshing(true);
                        }
                    }
                });

这样轮子就能在开始的时候出来了，
但是我说的意思是，在你的ViewPager，的图片加载那边用用一个轮子，哈哈，不用显示进度都可以，我在想可以用FrameLayout来加应该也可以

**Comment by cooliean** [comment]
有点类是微信朋友圈的图片效果，

**Comment by cooliean** [comment]
还有一个问题就是我一直想用Realm，但是一直都没有用，你觉得这个效率高点，还是SQLLite高点呢。

**Comment by xingrz** [comment]
图片加载指示，其实 Picasso 是有这个功能的，只是我没做（懒癌…`_(:зゝ∠)_`）

Realm 开发起来还是挺爽的，至于使用的效率其实不用太在意。

**Comment by cooliean** [comment]
Picasso 里面是一个placeholer吧，我想要一个自己的试图，比如progressbar，他也可以？

**Comment by cooliean** [comment]
我自己在布局里面加了一个，先将就用了，以后想到什么办法再说了。
